### ISSUE TITLE
Docs Update: Default export format

### ISSUE THREAD

**Issue by sebszocinski** [Roorda-ICT/statamic-entries-export#1]
Just a minor one but the docs say the [default export format](https://github.com/Roorda-ICT/statamic-entries-export#export-format) is `xls` but it's actually [`ods`](https://github.com/Roorda-ICT/statamic-entries-export/blob/master/config/entries-export.php#L19)

**Comment by jelleroorda** [comment]
Thanks for letting me know! I minor issue, but an issue none the less. I've updated the docs since updating the default for the configuration file would be a breaking change.
