### ISSUE TITLE
Export fails when standard Statamic date format is changed

### ISSUE THREAD

**Issue by Sennik** [Roorda-ICT/statamic-entries-export#4]
Export fails when standard date format is changed (I use the dutch format: d-m-Y), many european countries do.

```
Object of class Statamic\Query\OrderedQueryBuilder could not be converted to string/var/www/xxxxxx/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#30Error

                $value = $value->format('Y-m-d H:i:s');
            } elseif (!($value instanceof RichText)) {
                // Attempt to cast any unexpected objects to string
                $value = (string) $value; // @phpstan-ignore-line
            }
        }
```

Curious: Does this tool exports all bard sets too?

**Comment by jelleroorda** [comment]
Hey Sennik,

Could you please elaborate on the steps necessary to reproduce what you’re seeing? From what I see your error might not have to do anything with date formatting.

If I remember correctly it exports json-like fields (i.e. bard) as a json encoded string. This way the exported sheet could potentially also be used to import the rows again later.

**Comment by jelleroorda** [comment]
This issue is likely the same as #5, but I feel like it describes the issue more clearly. Closing this in favor of the other issue. If you can provide more information about the date actually bugging out we can reopen this issue.
