### ISSUE TITLE
Object of class Statamic\Query\OrderedQueryBuilder could not be converted to string

### ISSUE THREAD

**Issue by ddm-interactive** [Roorda-ICT/statamic-entries-export#5]
I am getting a fatal when exporting. PHP 8.1.14, Laravel 9.50.2, Statamic 3.4.3.

All I did was install the add-on, went to the utility page, selected any of my collections and clicked download. 

Not sure if this will help: 
![image](https://user-images.githubusercontent.com/110059296/227988924-9ba99a82-8f25-4517-8518-402526aad18f.png)

Thanks

**Comment by jelleroorda** [comment]
Hey thanks for reporting. I’ll have a look some time soon.

**Comment by ddm-interactive** [comment]
Any follow up?

**Comment by jelleroorda** [comment]
Hi ddm,

I’m currently on a vacation so it won’t be for the next few weeks, you can have a stab at a PR in the mean time if you can.

You can then use a composer patch to use it in your projects.

**Comment by jelleroorda** [comment]
Sorry for the delay. Pretty sure this should fix the issue: https://github.com/Roorda-ICT/statamic-entries-export/commit/ae26eb4b56917407a1c303ce1446da85456a0ec0

Can you verify whether this fixes your issue if you're running Statamic 4.0? You can install the master branch by requiring the `@dev` version in your composer.json for the package. So something like:
```
"roorda-ict/statamic-entries-export": "@dev",
```

**Comment by jelleroorda** [comment]
Should be fixed in the 2.0.0 release.
