### ISSUE TITLE
FR: Ability to define for which collections the export action should be available

### ISSUE THREAD

**Issue by robdekort** [Roorda-ICT/statamic-entries-export#6]
Brilliant addon. Works like a charm. So thanks for that first and foremost :-).

It might not always make sense for editors to have the export action on any collection. Could be a nice touch to make this configurable.

**Comment by jelleroorda** [comment]
Heyo, nice feature request. I've released [version 2.1.0](https://github.com/Roorda-ICT/statamic-entries-export/releases/tag/2.1.0) which has support for excluding certain collections.

**Comment by robdekort** [comment]
Brilliant!
